### ISSUE TITLE
[Feature Request] Selectable Color

### ISSUE THREAD

**Issue by danmandle** [visionmedia/debug#137]
It would be nice to pass another param to be able to set a static color along with the label/namespace.

**Comment by feimosi** [comment]
I've noticed that the API has changed since the last comment. Now you need to assign a color name from the following set: `[ 'lightseagreen', 'forestgreen', 'goldenrod', 'dodgerblue', 'darkorchid', 'crimson' ]`. Also you don't need to check against useColors. Still it'd be nice to be able to set a color next to the logger name.

**Comment by Soubkia** [comment]
It would be nice if there was a mapping or it integrated with a [color library](https://www.npmjs.com/package/colors) so that you could do something more concise.

```javascript
var debug = require('debug'),
      log = debug('Application');

log.color = 'red'; // same as \e[31m
log('foo');
log.color = 34; // blue
log('bar');
```

I think [this](http://misc.flogisoft.com/bash/tip_colors_and_formatting) has all the mappings if integrating a color library is too heavy handed.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < child debug instances + middleware should allow for this.  Feel free to discuss there

**Comment by Yalhu** [comment]
`debug.color='#f00'` can be used, why I can't see this on document. And is there any other useful API? 😆
