### ISSUE TITLE
debug.disable() does not disable?

### ISSUE THREAD

**Issue by swook** [visionmedia/debug#150]
```
process.env.DEBUG="*";
var debug = require("debug");
var log = debug("app:log");
log("Should show");
debug.disable();
log("Shouldn't show");
```

The above snippet does not work as expected.

The disable function should remove namespaces instead of trying to enable nothing.
https://github.com/visionmedia/debug/blob/master/debug.js#L159

**Comment by CumpsD** [comment]
`debug.enable(null);` does a real disable, removing the localStorage in the browser version, while `debug.disable()` simply sets it to an empty string.

**Comment by ibc** [comment]
`null == ''` returns false, so @CumpsD is right and this is a bug in the code. `debug.disable()` should call to `exports.enable(null)` rather than `exports.enable('')`.

Anyhow, calling to `exports.enable(null)` will just disable the debug for future created debug instances (that is what this issue is about).

**Comment by ibc** [comment]
Another problem is that calling  `debug.enable('stuff')` enables future debug instances whose prefix matches "stuff", but the DEBUG variable (or the "debug" item in LocalStorage in the browser) is overridden with just "stuff" (this is, just the last prefix given to `debug.enable()`).

This is inconsistent.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < V3 should solve this
