### ISSUE TITLE
Log date not in GMT format

### ISSUE THREAD

**Issue by ibc** [visionmedia/debug#157]
When redirecting the stderr to a file, `debug()` appends the datetime in GMT format, which is not very friendly. Is there a way to setting the datetime format?

**Comment by jesucarr** [comment]
The problem with that approach is that every debug instance will use that formatArgs. Is there a way to change the formatArgs in a per instance basis?

Example (this doesn't work):

    var log1 = debug('Application1');
    log1.formatArgs = function myFormatter(){...};
    log1('hello'); // uses myFormatter

    var log2 = debug('Application2');
    log2.formatArgs = function(){...};
    log2('hello'); // uses the usual formatter

**Comment by mooyoul** [comment]
@jesucarr

I think that is bad behavior because that breaks log style.
Anyway, If you really want to change log format per instance, You can extend `formatArgs` as Proxy.
[formatArgs code](https://github.com/visionmedia/debug/blob/master/debug.js#L113-L114) might be helpful to understanding mechanism.

```javascript
var debug = require('debug');

debug.formatArgsOrg = debug.formatArgs;
debug.formatArgs = function () {
    return 'function' === typeof this.formatArgs ?
               this.formatArgs.apply(this, arguments) :
               debug.formatArgsOrg.apply(this, arguments);
};


var log1 = debug('Application:First');
log1('hello world');

var log2 = debug('Application:Second');
log2.formatArgs = function () {
    var args = arguments;

    args[0] = 'wow doge' + ' ' + args[0];

    return args;
};
log2('hello world?');
```

![2015-03-29 9 50 44](https://cloud.githubusercontent.com/assets/2101743/6885513/b11dcc7c-d65d-11e4-81bb-188f03323244.png)

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < time configuration option for V3 api.  Feel free to take a look and discuss there

**Comment by justinmchase** [comment]
Just for posterity, because it threw me off for a little while, the example that @mooyoul has in his first reply doesn't quite work, head over to the actual function in debug and copy its contents and go from there instead.

- [Here is the node formatter](https://github.com/visionmedia/debug/blob/master/src/node.js#L106)
- [Here is the browser formatter](https://github.com/visionmedia/debug/blob/master/src/browser.js#L78)
