### ISSUE TITLE
No any output while using debug

### ISSUE THREAD

**Issue by samundrak** [visionmedia/debug#223]
I just installed and required debug in my project;
var debug = require('debug')('http');

and if i do debug('testing')
then no any output is done

but if i console.log(debug)
i see this message 
{ [Function: disabled] enabled: false, namespace: 'http' }

where i am going wrong?

**Comment by dcsan** [comment]
you have to set an env var when you run your app

DEBUG="*"  node app.js

read the docs for more info on namespacing.

**Comment by nikoskleidis** [comment]
This also occurred in my project too. 
I am using this:
DEBUG=app:*
in my .env file and I am using it like this in my files
import _debug from 'debug';
const debug = _debug('app:ComponentName');
debug('start component');

But I cannot see any logging in my console

**Comment by dcsan** [comment]
maybe the colon throws off the regex? have you tried other ways?

**Comment by nikoskleidis** [comment]
Thank you for your quick reply.
I am using this kit in my project: https://github.com/davezuko/react-redux-starter-kit#usage
I have narrowed down the problem and I realized that on the node console I see the debug as expected. The problem is on the browser's console in which I see no logging. I use google chrome.

**Comment by nikoskleidis** [comment]
Figured it out! I needed to run this : localStorage.debug="app:*" on the browser in order to work properly. Thanks again for your interest!

**Comment by mooyoul** [comment]
/ping @TooTallNate This is another closable issue ✅
