### ISSUE TITLE
DEBUG=+ breaks app

### ISSUE THREAD

**Issue by radare** [visionmedia/debug#288]
By setting this value to the DEBUG environment variable, it generates an exception that can only be catched like this:

``` javascript
try {
  const debug = require('debug');
} catch (e) {
  console.log('Invalid DEBUG environment value');
}
```

this seems like an anti-pattern to me, so maybe `.enable()` should handle the exceptions in the RegExp construction and just not set any value in DEBUG.

is this expected behaviour?

**Comment by SidneyNemzer** [comment]
Can this be reopened? This is still an issue because #250 was reverted not long after being merged.

https://runkit.com/sidneynemzer/5db9080a4b936b001982487d

```js
const debug = require("debug")
debug.enable("+") 
// -> throws: Invalid regular expression: /^+$/: Nothing to repeat
```

What should this case do instead? I think it would be nice to log an error because a variable like `DEBUG=+` might be intended to enable logging. If it slightly failed, it would be hard to debug (pun intended).

I'm happy to open a PR if we decide what to do instead.
