### ISSUE TITLE
Missing documenttation on fomaters

### ISSUE THREAD

**Issue by agirorn** [visionmedia/debug#293]
I can't seam to find the documentation on what formaters are available and how they work.

So far I have found 2

``` javascript
var debug = require('debug')('test')
debug('string: %s', 'THE STRING');
test string: THE STRING +0ms
```

``` javascript
debug('string: %o', { key: "VALUE" });
test string: { key: 'VALUE' } +1m
```

Are there any other formaters?

**Comment by elmigranto** [comment]
It is probably the same as [`util.format`](https://nodejs.org/dist/latest-v6.x/docs/api/util.html#util_util_format_format).

**Comment by nkolban** [comment]
Reviewing the code, it does indeed use "util.format".   The action from this issue will be to mention that in the programmer's guide and provide a link to util.format:

https://nodejs.org/api/util.html#util_util_format_format

**Comment by agirorn** [comment]
When you talk about the programmer's guide do you mean https://github.com/visionmedia/debug/wiki ?

**Comment by nkolban** [comment]
I'm imaging a programmer who comes along and wants to use the debug package.  In order for them to use the package, they will look for a "programmers guide" ... this will be a document describing how to use the package and the options available for the APIs.  Whether this is a PDF, a web page, the Wiki or a README.md ... all of those are options.  When I talk about a "Programmer's Guide" I am thinking more in the abstract concept of it rather than in a specific place.   In this example, probably the Wiki is ideal with a reference to the Wiki in the README.md of the project.

**Comment by agirorn** [comment]
So for now, should I add this to the wiki or make a pull request that mentions this in the README ?

**Comment by thebigredgeek** [comment]
Happy to take a PR for this @agirorn

**Comment by thebigredgeek** [comment]
This should be fixed
