### ISSUE TITLE
debug cannot working when i use "[]" ?

### ISSUE THREAD

**Issue by wenkanglin** [visionmedia/debug#312]
**the question is : when i use the code below**

`process.env.DEBUG = '[webpack:dev]'`
`const debug = require('debug')(process.env.DEBUG)`
`debug('start')`

it doesn't work, because `process.env.DEBUG`  has '[]' character. when i use the code below: 

`process.env.DEBUG = 'webpack:dev'`

it does work well!
**so, if i want to use '[]', what should i do ?**

**Comment by zacronos** [comment]
@wenkanglin: a PR that fixes this issue was merged very recently (https://github.com/visionmedia/debug/pull/250#issuecomment-255548251).  However, I don't think a new npm release has been published with that fix included.  Once that happens, updating your version of `debug` should be enough.  In the meantime though, to use brackets or other regex special characters, you'll need to do 1 of 2 things.

Either:
* use the github master branch version of `debug` (specified as `"debug": "git://github.com/visionmedia/debug.git"` in your package.json dependencies)
* or else escape those special characters yourself, probably along the lines of `process.env.DEBUG = '\\[webpack:dev\\]'`.  However, note that this solution will STOP working once you start using a version of `debug` that includes the PR mentioned above.

**Comment by wenkanglin** [comment]
good ! I use the first solution, it does work well ! Thank you for your answser !

**Comment by adi518** [comment]
Really old issue, but I still can't get a bracket namespace to work, even when I managed to escape the brackets properly: `'\"[OWMR]\"'`.

**Comment by Qix-** [comment]
I would suggest against using anything other than `/[a-zA-Z0-9_]+/` as your namespaces. It's never been guaranteed that they're valid and the next version will most likely forbid it.
