### ISSUE TITLE
[RFC] Code style

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#397]
Discuss!

**Comment by TooTallNate** [comment]
I like [`xo`](https://github.com/sindresorhus/xo)'s defaults lately.

**Comment by dougwilson** [comment]
Any style is good. The Express JS project settled on `standard` just because... choose something :) That's pretty much my only comment here: just pick something, with the only argument being to choose a pre=built set vs trying to maintain your own set.

**Comment by thebigredgeek** [comment]
@dougwilson @TooTallNate yeah I like XO as well.  Might as well go with this

**Comment by Qix-** [comment]
I'm also :+1: for `xo` simply because it prevents PRs from being riddled with commonly (mis)used bad practices.

**Comment by billthornton** [comment]
Hi @Qix-,

Would it be fair to consider this a breaking change (i.e. a 4.0 change) since it removes compatibility with an older version of node (v4)? I realise node 4 is now unsupported but this may end up breaking a lot of peoples builds that make use modules which depend on the `debug` package and cannot yet upgrade (such as it's caused the `pm2` library to not work for us this morning).

Just thought I'd let you know incase this wasn't the intention.

**Comment by Qix-** [comment]
@billthornton #603 :)

**Comment by eastwood** [comment]
It appears that this PR has broken some builds for us. We're getting some issues with older versions of uglifyJS whereby the es6 syntax is incompatible with this version. The debug package ended up making it into our vendor bundles. I'm not sure if it' too late to bump this change to major version, but a heads up in any case

**Comment by Qix-** [comment]
@eastwood see #603 and #610 please.
