### ISSUE TITLE
[RFC] Doc generation

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#401]
discuss!

**Comment by Qix-** [comment]
What kind of generation? You mean generating docs from source, or using something like restructured text?

IMO this package isn't complex enough to warrant anything beyond a readme. Most simple node modules nowadays use the readme for such documentation.

---

This is a rather old ticket and I'm simply trying to do some housekeeping, so please feel free to close this if it's no longer pertinent (especially since v3 is out already).

**Comment by Qix-** [comment]
Closing since the API of `debug` has been pretty much exactly the same since the 0.x releases 😅
