### ISSUE TITLE
Can i choose a namespace color?

### ISSUE THREAD

**Issue by bertolo1988** [visionmedia/debug#432]
```
error = require('debug')('app:error');
```
Can i make error to be exclusively red?

**Comment by TooTallNate** [comment]
Selecting the color itself is a bit wonky since you have to know the index in the array of the color that you want, but basically just set the `debugInstance.color` property of the instance to one of the values in the `debug.colors` Array. So for red you want index 5:

```js
const createDebug = require('debug')
const error = createDebug('error')
error.color = createDebug.colors[5]

error('foo')
```

![screen shot 2017-03-07 at 8 41 50 am](https://cloud.githubusercontent.com/assets/71256/23667186/ef6fb188-0311-11e7-8e83-dac6e61a7f9f.png)

**Comment by bertolo1988** [comment]
Thanks alot @TooTallNate.

**Comment by TooTallNate** [comment]
Can you show me an example of what you're thinking?

**Comment by bertolo1988** [comment]
```
var debug = require('debug);
error = debug('app:error', "red");
var something = debug('app:something');
```

`error` would be red.
`something`, since color was not specified, will grab a color that is not red.

**Comment by TooTallNate** [comment]
This would require maintaining a list of "taken" colors, instead of just iterating through the numbers. Kind of unnecessary in my opinion for a feature that I don't think would be too heavily used.

Thanks for the suggestion but honestly, probably not. I think the solution above should be good enough. Hope you understand in the name of keeping this module minimalist!

**Comment by Yalhu** [comment]
@TooTallNate  All the debug's output is `console.info`(maybe `console.log`), including error `var error=debug('debug:error')`.It is just a different color of namespace, not a real `console.error`. What's more ,its color isn't red.

How should I output a debug different infomation of `info/log/warn/error`, which I can filter on chrome console. wheather they are on a same color. Or same background color, different text color to distinguish `info/log/warn/error`.  May be same feature with #514
