### ISSUE TITLE
Feature: Customized colours for specific debug statements

### ISSUE THREAD

**Issue by mtpultz** [visionmedia/debug#514]
It would be nice to be able to set the different output streams to be a specific colour that resemble the level being logged.  Currently the colours are a fixed list that doesn't provide any logical visual clue to the debug statements that might be expected - `exports.colors = [6, 2, 3, 4, 5, 1]`.  If it were made to be customizable using Chalk declarative styles, and left to default back to the existing setup colours could be personalized and associated to the debug statement.  

Also, putting the onus on the developer to customize the styles means no one can complain about the colour, tint, bold, underlined, etc based on preference or OS, since they just need to pass in a chalk chain to wrap the module namespace with whatever they want, and can use chalk in their own output.

**Current Colours**
log = yellow
info = pink
debug = green
error = light blue

**Feature Colours**
log = `chalk.greenBright`
info = `chalk.cyanBright`
debug = `chalk.yellowBright`
error = `chalk.redBright`

**Comment by jacobq** [comment]
Would you please clarify what would be affected by this coloring? Is it the logger/name, the message/content, or something else?
![image](https://user-images.githubusercontent.com/1633459/37283205-1cfcea90-25c5-11e8-9fc1-f57809e17201.png)
![image](https://user-images.githubusercontent.com/1633459/37283363-bb58b2a0-25c5-11e8-957b-72efc6bf941c.png)

If it's just the content then this doesn't seem to be much different than something like this:
```js
const chalk = require('chalk');
const debug = require('debug');
const logger = debug('foo:bar');
logger.enabled = true;
const log = (...args) => logger(chalk.greenBright(...args));
log('this string is green', chalk.yellow('this one is yellow'), 'back to green here');
```

If the goal is to color by severity then why not just prepend a colored prefix?
```js
const chalk = require('chalk');
const debug = require('debug');
const logger = debug('foo:bar');
logger.enabled = true;
const log = (...args) => logger(chalk.greenBright('log:'), ...args);
const logInfo = (...args) => logger(chalk.cyanBright('info:'), ...args);
const logDebug = (...args) => logger(chalk.yellowBright('debug:'), ...args);
const logError = (...args) => logger(chalk.redBright('error:'), ...args);
log('default style log message');
logInfo('just FYI');
logDebug('x= 31337');
logError('<-- big scary error!')
```
![image](https://user-images.githubusercontent.com/1633459/37284345-3297e748-25c9-11e8-8f82-87063beac356.png)

If it's the logger name / label then I'm not sure that it makes sense for each module to be able to set this by itself (though perhaps it would be nice to be able to set a default). While I like to idea of making it easier to customize coloring, I think it might be better handled by another module that wraps `debug` in order to keep things clean here.

**Comment by Qix-** [comment]
Agreed, this is an anti-pattern IMO, and something that would add needless complexity.
