### ISSUE TITLE
better Browser Support without refresh the page

### ISSUE THREAD

**Issue by mydearxym** [visionmedia/debug#534]
hi there ~

in the doc: 

>Debug's enable state is currently persisted by localStorage. Consider the situation shown below where you have worker:a and worker:b, and wish to debug both. You can enable this using localStorage.debug:
> localStorage.debug = 'worker:*'
And then *refresh* the page.

is there a way to not `refresh` the page and make it work ?

**Comment by czaarek99** [comment]
The reason for this seems to be because it's just coded that way. You can [see here that the load() method that reads the local storage only gets called when the debug object is created](https://github.com/visionmedia/debug/blob/71169065b5262f9858ac78cc0b688c84a438f290/src/common.js#L232). We could listen for the [storage event](https://developer.mozilla.org/en-US/docs/Web/Events/storage) to know when to update the state.

**Comment by czaarek99** [comment]
It seems like implementing this would lead to huge breaking changes with the current way debug is coded. To be able to change the namespaces for debug instances live you'd need to somehow expose [this method](https://github.com/visionmedia/debug/blob/71169065b5262f9858ac78cc0b688c84a438f290/src/common.js#L157) to browser.js.

What you could do is listen to the storage event yourself and just recreate your debug instances this way they would re-read the localStorage.

**Comment by leahciMic** [comment]
@mydearxym the `debug` module exposes an `enable` method. So if you do this:

```js
localStorage.debug = '';

const debug = require('debug');
const log = debug('MyApplication:log');

log('blah');  // not logged

debug.enable('*');

log('blah'); // logged
```

**Comment by Qix-** [comment]
@mydearxym Did @leahciMic and @czaarek99 answer your question?

**Comment by mydearxym** [comment]
@Qix-  @leahciMic  @czaarek99   sorry for the delay.
