### ISSUE TITLE
Add in sourcemap support

### ISSUE THREAD

**Issue by useafterfree** [visionmedia/debug#551]
Currently there is:
https://www.npmjs.com/package/gulp-sourcemaps

But it would be nice to have this natively?

Maybe this already exists?

**Comment by Qix-** [comment]
We don't output source files. There is no need for source maps.

**Comment by cmonacaps** [comment]
Hi, have I found the right issue?  Perhaps this is referring to something else.

<img width="554" alt="Screen Shot 2020-04-27 at 6 02 03 PM" src="https://user-images.githubusercontent.com/50930812/80425208-364fa680-88b1-11ea-8b7a-3b9b1fc506ae.png">

I have webpack set up to use some plugin, so that if I click at the link included with every console line (it's `browser.js?34eb:183` on nearly all the lines, it opens the source code directly in chrome dev tools.  For example at `browser.js?34eb:183` I find:

![source_map](https://user-images.githubusercontent.com/50930812/80425682-271d2880-88b2-11ea-9ca8-72a31e74556c.png)

Which is `debug` point of call to the logger.

Of course I'm more interested in the line where I called it.  Maybe there's no way to put that, I also didn't find a way to walk up the stack, not sure but guess just the line number is stored not the whole context with each line

When the source map's working you can just do

```
. . . render = props => sequence( debug( props ), . . .
```
and jump right in without trying to hang a breadcrumb off each `debug` line

**Comment by Qix-** [comment]
This has nothing to do with that. That's because the actual call to `console.log` is within `debug`.
