### ISSUE TITLE
Is it possible to control whether or not to use Date#toISOString() ?

### ISSUE THREAD

**Issue by qiulang** [visionmedia/debug#574]
> When stdout is not a TTY, Date#toISOString() is used ...

I hit the problem that when using vcode, set "outputCapture": "std",  `Date#toISOString() ` will be used automaticlly instead of showing millisecond diff in vscode debug console(without setting it there will no log at all https://github.com/Microsoft/vscode/issues/41600)

So is it possbile to set whether to use  Date#toISOString() or not ?

**Comment by Qix-** [comment]
This is a (continual) problem in the vscode debug console. If they want TTY support then they need to report to programs that the stdout/stderr file descriptors are interactive TTY sessions.

**Comment by Spown** [comment]
Why is this issue closed?

>If they want TTY support then they need to report to programs that the stdout/stderr file descriptors are interactive TTY sessions.

I don't know what do you mean by "interactive TTY session" but ``process.stdout.isTTY`` is ``true`` with ``"outputCapture": "std"`` in VSCode. And anyway nobody asked for a fix for VSCode problem here. qiulang has asked for a way to control the timestamping format. Irregardless of environment.

Personally I would like to have this option because diff timestamps show nonsense in async and with multiple submodules
![](https://drive.google.com/uc?id=1t6MumEH3pxbQ7d6wM88er7_ZMkzPWQfA)
I would much rather see actual time or better yet a way to format my own timestamp (while developing I probably don't need DD.MM.YYYY and a timezone, just HH:MM:ss:SSS)
