### ISSUE TITLE
messd up in worker of cluster

### ISSUE THREAD

**Issue by bi-kai** [visionmedia/debug#588]
it's ok in master, but messd up in worker of cluster.
![image](https://user-images.githubusercontent.com/15070379/42120963-2a12182a-7c57-11e8-991f-ce79bb174c11.png)
![image](https://user-images.githubusercontent.com/15070379/42120965-33af7008-7c57-11e8-9a15-ceabbbd43b6d.png)
![image](https://user-images.githubusercontent.com/15070379/42120967-3a0975ca-7c57-11e8-959e-4ce643f46e9f.png)

it's ok with `console.log`:
![image](https://user-images.githubusercontent.com/15070379/42120978-557d259a-7c57-11e8-9a55-cd9af9d4e631.png)

it turns better when I use `setTimeout` between debug log.
how to fix this?

**Comment by Qix-** [comment]
This isn't `debug`'s fault. This is because you have three processes printing out to stderr (a non-line-buffered file descriptor) and whatever it is that's managing your cluster isn't performing line buffering for you.

There's nothing `debug` can do about this other than to output to stdout, which isn't the correct solution. Please open a ticket with the cluster manager you're using.

**Comment by bi-kai** [comment]
@Qix- It seems to be ok on linux, I really don't know how to make it right on win.
how to perform beauty on each platform?
