### ISSUE TITLE
Use console.debug() instead of console.log() where available (e.g. browsers)

### ISSUE THREAD

**Issue by Qix-** [visionmedia/debug#600]
Currently `debug` output in the browser gets `console.log()`'d.

However, browsers have a `console.debug()` call (nonexistent in Node.js, of course) that would group all `debug` output into its own category, perhaps making it easier for debugging in the browser when trying to look at regular application output.

Relevant lines:

https://github.com/visionmedia/debug/blob/master/src/browser.js#L112-L114

Thoughts?

**Comment by picwellwisher12pk** [comment]
I am very new with this things. can you guide me a little how I can use debug on browser? I am using Webpack to make a Firefox addon. Any help is appreciated.

**Comment by Qix-** [comment]
@nmccready I don't see how your response is relevant at all. We're already using `console.log()` everywhere. I'm simply suggesting the use of `console.debug()` in the browser instead, since it's available there and would allow people to better filter out log messages using inspector tools.

Since I'm not getting much intelligible feedback on this, I don't see any objections and I think it's an improvement to better match how the behavior works in the console.

**Comment by targos** [comment]
`console.debug()` is available in Node from version 8, and would also be filterable with inspector tools if node is run with `--inspect`.

**Comment by Qix-** [comment]
@targos TIL. Yeah I figured the logic would be `(console.debug || console.log)(...)`.

**Comment by danielweck** [comment]
Just a heads-up about this code change: by default the Chromium web console (maybe others too) filters messages at the `info` level which excludes `console.debug()`, so developers will have to *explicitly* activate the `verbose` level to see messages outputed by `debug()` in versions `>4.1.0`. I have just verified this new behaviour in an Electron app using the `debug()` code from the master branch (instead of the officially-release version `4.1.0`).
https://developers.google.com/web/tools/chrome-devtools/console/
This is a minor breaking change, but as long as it is well-documented, this should not cause `debug()` users too many headaches, right?  :)

**Comment by Qix-** [comment]
Seeing as how that's kind of how terminal applications work currently, this is fine. I was aware of this behavior when making the change, hence why it's marked for the 5.x release.

**Comment by PieerePi** [comment]
Frankly speaking, it's not a good idea. When I upgraded the package from 4.1.1 to 4.2.0, I couldn't find my debug logs until I switched to the 'user messages' category.

It's not user friendly, although that chould be Chrome's problem.

**Comment by Qix-** [comment]
@PieerePi That is definitely chrome's problem, not ours. This library isn't built for only chrome.

---

Locking this as I don't think there's much more discussion to be had here.
