### ISSUE TITLE
No longer works with uglify-js

### ISSUE THREAD

**Issue by ibc** [visionmedia/debug#610]
I think that, due this [commit](https://github.com/visionmedia/debug/commit/b3f8f8e683915ef4fae3a77cbcebc6c410e65a8c) `debug` no longer works with `browserify` + `gulp-uglify` (which uses `uglify-js` internally):

```
 GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword (const)
File: /Users/ibc/xxxx/src/myApp/myApp.js
Line: 24207
Col: 1
```

If I use `browserify` without `uglify` and check the generated bundled JS file, it contains:

```js
const c = 'color: ' + this.color;

// and many other ES6 stuff
```

I don't think this is intentional, am I right?

**Comment by Qix-** [comment]
It is intentional. Uglify doesn't work on ES6 code. Use `gulp-uglify-es` instead.

**Comment by ibc** [comment]
`gulp-uglify-es` uses `uglify-es` which is buggy and unmaintained. You may mean `gulp-terser` and [terser](https://github.com/fabiosantoscode/terser).

Anyway, are you aware that `webpack` requires that NPM dependencies are ES5? I mean: expect **lot** of complains due to this change in `debug`.

**Comment by ibc** [comment]
Sure, I know babel. I also know that default webpack configuration (that which is widely used) does not convert `node_modules/*` to ES5:

Just a reference: https://github.com/zeit/next.js/issues/3564

**Comment by Qix-** [comment]
@ibc I used to work at ZEIT. We used Babel very effectively where needed. You don't want your entire node_modules compiled because that would be silly.

Further, modules providing a transpiled version is unsustainable. Please read https://github.com/zeit/next.js/issues/3564#issuecomment-418495379 as he is pretty **objectively** correct.

I won't discuss this issue any further. I suggest googling further as there are **leagues** of prose on this matter available to you through various searches. This is where the JavaScript ecosystem is headed and has already been adopted pretty much everywhere else.
