### ISSUE TITLE
Question: why the leading spaces?

### ISSUE THREAD

**Issue by morgs32** [visionmedia/debug#619]
Why the leading spaces here?
https://github.com/visionmedia/debug/blob/master/src/node.js#L169

**Comment by Qix-** [comment]
Not sure, it was an aesthetic decision I believe that predates my maintainership. However I appreciate it because on some VGA server monitors, the onboard VGA chip doesn't get overscanning just right and the first column can get cut off.

Just my $0.02. I don't believe they're there when you're piping to a file, though.

**Comment by aalimovs** [comment]
@Qix- should we look at env variable disabling it, or passing a number of how many leading spaces there will be?

**Comment by Qix-** [comment]
@aalimovs see #582.
