### ISSUE TITLE
No logging from code compiled with webpack? 

### ISSUE THREAD

**Issue by tim-rohrer** [visionmedia/debug#637]
I'm not sure if this is related to #301 as I don't get errors.

But, I don't get any output from `debug` calls in any compiled source. 

I inherited the code I'm working with. It does use webpack to compile the source. My `npm` start script will provide `debug` output, but once the server starts, `debug` in the source code doesn't produce any output.

A module central to my app is `App.js`, which includes `Class App` which extends `React.Component`. I have this at the top of the file:
`const debug = require('debug')('my-app:mainapp');`

And in the constructor:
`debug('App constructed');`

However, when the app starts, the `App constructed` message is not printed.

I realize I'm not giving you a lot to go on; I'm hoping you can help focus my troubleshooting. I have tested `debug` in several other module files.

**Comment by tim-rohrer** [comment]
I have read the readme attached to this project, and the Wiki. 

I was trying to get output to the terminal (stderr?), not the browser console. I have used `debug` before and have mimicked the approach I did before, but I get different results with the compiled code.

If I'm missing something obvious...

**Comment by Qix-** [comment]
I'm pretty confused, how do you have both a browser window and a terminal window in production? If debug is being used in the browser, it's going to go to the browser window. If it's running in a node.js process, it's going to go to the terminal.

If you're using the Node.js debugger, the output is going to go to the terminal in most cases. There's an issue somewhere to fix this but right now it's not really specified how it should work when you're using the debugger (which seems strange, I know).

The problem is detecting if the debugger is active and if there's a browser being logged to is _really_ hard.

I don't see anything actionable here as of now. This might change in the future. Sorry for the confusing behavior :|
