### ISSUE TITLE
How to use with react-native?

### ISSUE THREAD

**Issue by lloydwatkin** [visionmedia/debug#640]
Is there a way to get this outputting to console with react native?

I note the code determines that the simulator is running as node, rather than a browser which may or may not be correct. Also how to I set which namespaces should be enabled?

Thanks!

**Comment by Qix-** [comment]
I've not used React Native so unfortunately I can't give you any firsthand insight (maybe someone from the community can) but for browsers you specify the namespaces in `localStorage` (see the readme about that).

As for not detecting the right implementation (node vs browser) this could be a bug depending on which one should be used for React Native.

For testing purposes, what happens when you `require('debug/dist/debug')` instead? Make sure that your `localStorage` is set up as I mentioned above. Does that show information?

**Comment by Qix-** [comment]
I'm sure it's not the first time someone has used `debug` with React Native. I'm sorry for not being much help ._.

**Comment by lloydwatkin** [comment]
Ok, here's a workaround that works for me (and works across console for testing and simulator):

```javascript
// eslint-disable-next-line valid-typeof
if (typeof window !== 'undefined') {
  process.type = 'renderer'
  window.localStorage = {
    debug: Config.DEBUG_LOG || '*',
    getItem: () => {
      return Config.DEBUG_LOG || '*'
    },
  }
}
```

`Config.DEBUG_LOG` is coming from an `.env` file and [react-native-config](https://www.npmjs.com/package/react-native-config). However it would be great if this "just worked" so I'll see if I can find a nice way to get the data into `debug` and make a PR in future :)

**Comment by Qix-** [comment]
Honestly I think that's the most elegant solution - using `.env` with react-native-config. Using `'*'` by default goes against the goals of `debug`.

Thanks for the research, however!
