### ISSUE TITLE
Listing all available targets?

### ISSUE THREAD

**Issue by jehon** [visionmedia/debug#722]
Hello

I would like to list all targets that are available for debug.

I would suggest a list of the strings used:

```
const debugFactory = require('debug');
var a = debugFactory('worker:a');
console.log(debugFactory.getAllAvailableTargets());
// result:
// [ "worker:a" ]
// or
// [ "worker", "worker:a" ]
```

I have read the comments of the #255, that is suggesting that it would be a memory leak. Is that so? If we cache the "keys" and not the objects, I don't think that it would be a memory leak?

I could submit a PR if this idea is accepted.

**Comment by Qix-** [comment]
If this is just for debugging purposes, `require('debug').names` will give you the list of regexes that match the enabled namespaces.

Otherwise, this would be storing strings indefinitely, which might leak given the current implementation. #678 has more information about that, and #425 currently discusses `.enable()` a bit more too.

I'll consider this but right now it's not something I want to support until v5.

**Comment by jehon** [comment]
Thanks Qix,

I will see if I can help on the memory leak, as a first step before discussing this one :-)

I hope your house move was fine, your new job is great and your family bring you hapiness !

Have a nice day

**Comment by Qix-** [comment]
Sorry for the delayed response - thank you for the kind words @jehon ^^
