### ISSUE TITLE
`.enabled()` logic incorrectly returns true when namespace contains asterisk

### ISSUE THREAD

**Issue by Qix-** [visionmedia/debug#741]
```javascript
debug.disable('*');
debug.enable('foo');
assert.not(debug.enabled('bar'));
assert.not(debug.enabled('bar*')); // throws; returns true
```

Has to be solved in two ways:

- More stringent checks on namespaces (as they shouldn't contain asterisks)
- Remove the check for `ns[ns.length-1]==='*'`, which makes absolutely no sense

**Comment by HaroldPutman** [comment]
yes!

**Comment by jasonk** [comment]
According to the documentation, this is by design:

>  If you append a "*" to the end of your name, it will always be enabled regardless of the setting of the DEBUG environment variable.

**Comment by Qix-** [comment]
Aha thanks @jasonk, definitely archaic functionality even I didn't know about.

I suppose there's really nothing to do here unless we want to break backwards compatibility.

**Comment by HaroldPutman** [comment]
That's certainly unexpected documented behavior. I was hoping to be able to tell if any of a "family" of debuggers is enabled by calling `debug.enabled('dealer:*')`. After reading the code I realize this is not an easy problem since the enabled debug namespaces are stored as regular expressions.

In the end I solved it like this:
```
const isDebugEnabled = require('debug').names.reduce((state, name) => {
      return state || name.toString().startsWith('/^dealer:');
    }, false);
```
Note that I am searching for a regular expression pattern. This is not foolproof, but maybe someone with a similar need can reuse this solution.

**Comment by stephenhandley** [comment]
naively seems like ```
if (name === '*') {
  return true;
}``` would be less surprising.

would actually be interesting to know if anyone made use of this
