### ISSUE TITLE
Transpile to ES5

### ISSUE THREAD

**Issue by stnwk** [visionmedia/debug#745]
Hi :) Thank you for your work on this package!

Please re-consider this issue: https://github.com/visionmedia/debug/issues/668

It is a major blocker and breaking-change that was released under a minor version upgrade on this package.

You stated `transpile your dependencies just like everyone else does` - unfortunately that is not true and creating a lot of problems in the JS ecosystem.

Some resources:
- `create-react-app` which is the go-to tool in `react` world to easily create react apps does not transpile depencies.
- There are a lot of blog posts and other resources out there explaining the difference between **transpiling** and **compiling**
- Here's one article explaining why it's a bad idea, especially for big projects with a lot of dependencies to start transpiling all of their node_modules: https://levelup.gitconnected.com/lessons-learned-from-a-year-of-fighting-with-webpack-and-babel-ce3b4b634c46 - Of course everyone **compiles** there dependencies into a build, but **transpiling** each and everyone of them is not a good idea and also just not feasible.
- Here's another issue in another package, where the same problem was discussed and the differences and importance was explained pretty well: https://github.com/mobxjs/mobx-react-lite/issues/63#issuecomment-462680017
- **Especially this comment here is making the point super clear:** https://github.com/mobxjs/mobx-react-lite/pull/66#issuecomment-463619255

Because our app still has to support IE11, we are effectively prevented from upgrading packages that then use your `debug` package on a latest version, which breaks IE11 support although they did not release a major upgrade because this package did not do so. The only way we can get around is by transpiling our node_modules, which is not feasible for big packages and gets really cumbersome to manage exceptions at a larger scale.

Happy to discuss & help you understand this problem and the impact you and this package are having on the entire eco-system. I really hope you reconsider.

Sincerely,
Stefan

**Comment by Qix-** [comment]
Sorry, no. It is no longer the belief that transpiling node_modules is a bad idea. The future is ES6 and beyond; IE11 is the last remaining browser that is supported that subsequently does _not_ support ES6 at all. This is what babel is made for.

I'm not trying to be mean about this, but transpiling `debug` to ES5 for releases is only going to resolve your IE11 incompatibilities until you hit the next module that is distributed as ES6.

Plus, transpiling isn't going to work for every use-case, either. It's a very application-specific process that I can't make decisions about.

I'm 100% aware of the arguments from both sides of the arguments - I've been writing javascript for almost 15 years now (ES3) and have been in the node community since 0.10. The transpilation debate is over now; Babel is how things should be done, and with modern bundlers is trivial to configure to do so.

`create-react-app` is a bloated generator; I don't personally support its use. It is not our (package maintainers') jobs to pick up the slack where `create-react-app` chooses not to do something. You are more than welcome to eject your application and create a bundler if you need to support archaic browsers.

Alternatively, learn to mount your own react apps - it's really not that hard (`parcel` is an excellent tool for this).

As stated in the comment when creating an issue, this is a decision that will not change. You're welcome to create an issue at `create-react-app` if you feel they should add a transpilation step.
