### ISSUE TITLE
Help understanding use of DEBUG prefix

### ISSUE THREAD

**Issue by NamedArray** [visionmedia/debug#794]
Can you please help me understand the context behind prefixing `DEBUG` on the command line, _in front_ of the js file?

Is `DEBUG` a special-purpose variable to the Node/NPM environment, or is `DEBUG` directly related to the debug NPM application you've created?

If I exclude `DEBUG` from my PM2 startup script, neither your package, nor `console.log()` will generate a log entry.

I should mention that I'm using Windows and PowerShell.  I need to experiment more with your package _outside_ of PM2 to get a better understanding.

Anyway, here is an example startup script for PM2:

        {
            "name": "TestProject69",
            "cwd": "C:\\Node_Apps\\TestProject69",
            "script": "app.js",
            "watch": true,
            "ignore_watch": ["node_modules"],
            "env": {
                "EXPRESS_PORT": 5001,
                "NODE_ENV": "development",
                "DEBUG": "express"
            }
        }

ALSO, is there any advantage to debugging everything `"DEBUG": "*"` vs debugging specific entries (like Express only)?

**Comment by Qix-** [comment]
Firstly, be sure you understand what [environment variables](https://en.wikipedia.org/wiki/Environment_variable) are. I can't tell from your post whether or not that's the case. :)

> Can you please help me understand the context behind prefixing DEBUG on the command line, in front of the js file?

Because shells (bash, etc.) generally require environment variables be specified prior to running a process.

> Is DEBUG a special-purpose variable to the Node/NPM environment, or is DEBUG directly related to the debug NPM application you've created?

Both, but only because `debug` was _inspired by_ the way Node.js allows the debugging of its internals. Realistically, most people don't enable any of the namespaces that Node.js responds to.

> If I exclude DEBUG from my PM2 startup script, neither your package, nor console.log() will generate a log entry.

The first part makes sense, as `debug` requires that namespaces are explicitly enabled (and none are enabled by default).

The last part does not - I think through some more testing you'll find that `console.log` _does_ output information. If not, then it's something unrelated to `debug` that's preventing it.

> ALSO, is there any advantage to debugging everything "DEBUG": "*" vs debugging specific entries (like Express only)?

No, not really. It just means you're going to get information you don't really need (it's usually a good idea to limit a program's output to what you're really interested in - this means perhaps turning on more verbose logs during development and then limiting them only to informational, warning or errors in production, etc).

**Comment by NamedArray** [comment]
It is very helpful, thank you!  I did some more reading after my initial question... Can I ask a couple of follow-ups?

It seems like env var `DEBUG=*`, or `DEBUG=express,http,myapp` acts like a "filter" for events emitted by packages in the application.  I guess this is sort of a way to enable/disable events?  Multiple packages can be separated by comma...  And, it seems you can specify the app's name itself to get a message emitted _oustside_ of express or http.

What is the `:` after the package?  Example:  `http:server` or `express:error`?  How do I identify what flags can come after the `:` for each particular module?  

ALSO, when declaring the the logger, I _think_ I can do something like this:
`const debug = require('debug');`
`const logger1 = debug('express');`
`const logger2 = debug('http:error');`
and also,
`const debug = require('debug')('express');`

Can you help me understand the syntax in `const debug = require('debug')('express');` is?

Is `(express)` a parameter I'm passing into `debug()`?  When I was playing around, it seems like a lot of the same syntax accepted by `DEBUG=` is also accepted by the parameter.

**Comment by Qix-** [comment]
> It seems like env var DEBUG=*, or DEBUG=express,http,myapp acts like a "filter" for events emitted by packages in the application. I guess this is sort of a way to enable/disable events?

Yes, the README covers this in pretty good detail by the way.

> What is the : after the package? 

It's a [namespace](https://en.wikipedia.org/wiki/Namespace) separator.

> ALSO, when declaring the the logger, I think I can do something like this:

Correct.

> Can you help me understand the syntax in const debug = require('debug')('express'); is?

`require('debug')` returns a function you call to create a new namespaced logger object, which you immediately call with 1 argument - `'express'`.

> Is (express) a parameter I'm passing into debug()? 

Yes.

> When I was playing around, it seems like a lot of the same syntax accepted by DEBUG= is also accepted by the parameter.

Yes, the readme explains almost all of this. 👍 


Going to close for now, I think the readme should be able to answer all of your questions! 🙂
