### ISSUE TITLE
Recent security vuln not picked up by `npm audit`

### ISSUE THREAD

**Issue by coreyvan** [visionmedia/debug#800]
This [issue](https://github.com/visionmedia/debug/issues/797) is not being picked up by `npm audit` when I'm trying to scan my app. There are a lot of dependencies that are using the vulnerable versions of debug.

Is there a quick way to pin a specific version of `debug` for every dependency? I'd rather not hack my package-lock manually. I'm new to Node so I'm not sure if this is an obvious question or not.

**Comment by Qix-** [comment]
> This issue is not being picked up by npm audit when I'm trying to scan my app

NPM still hasn't responded to me about the vulnerability status. Guess it's not high on their list of priorities. It won't show up in your audit until they address it themselves - it's not any sort of command I can personally run.

> Is there a quick way to pin a specific version of debug for every dependency?

Nope. However, the vulnerability only really causes you problems if you're passing unsanitized user input directly to it and using `%o` in Node.js. Otherwise, the vulnerability doesn't affect you. It's a very low severity vuln.

Most packages that don't pin versions will have picked it up for v3 and v4. If you're installing with `npm i debug` or `npm i debug@latest` then you'll get the latest patched version.

Otherwise, you should be fine. Most things aren't using `debug` in this way and thus it has a _very_ low chance of affecting you. And even then, it only happens after a certain size and doesn't have any risk of e.g. leaking user data. It's simply a denial-of-service, and a low-impact one; it'll slow down your application if you pass really long strings to the `%o` formatter on an affected version.

Just keep yours updated, and any other dependencies updated. It should be OK.

**Comment by Qix-** [comment]
Going to close this for now; let me know if there's anything else I can help with!

**Comment by coreyvan** [comment]
Thanks for the help!
