### ISSUE TITLE
Remove bad practice of writing process.env.DEBUG

### ISSUE THREAD

**Issue by sapkra** [visionmedia/debug#814]
In some projects an error occurs when building node.js applications with webpack.

It's a bad practice to write environment variables inside javascript, in my opinion. Environment variables should always be set by the environment. So the current solution should be refactored by using an own global variable with a fallback/default value of the `process.env.DEBUG` environment variable.

After this is fixed the problem will never appear again. Or is there any specific reason why you have to write `process.env`?

Some related issues:
https://github.com/visionmedia/debug/issues/301
https://github.com/mrsteele/dotenv-webpack/issues/271

**Comment by Qix-** [comment]
Writing environment variables is not a "bad practice", wherever did you get this idea?

Closing as there's nothing actionable here. The fact webpack bakes `process.env` has always been a weird feature, and not one I want to tiptoe around personally.

Sorry if this isn't the answer you're looking for.

**Comment by sapkra** [comment]
@Qix- I think this would be an easy fix and would solve this issue finally for a lot of people. Would it be fine for you if one is creating a PR for it?

**Comment by Qix-** [comment]
No, this is not something I'm interested in changing, sorry.

**Comment by sapkra** [comment]
Ok, now I'm very interested in the reason. Because as I understand it will not change how the library works, it wouldn't break anything, so what speaks against changing it, if not even you have to put effort in it?

**Comment by Qix-** [comment]
The only place it's happening is with `save()`. I'm not going to change that because it's part of the public API and would incur a major version release, which is not at all ready yet because v5 will be almost a complete rewrite.

So there is no worth in "fixing" this now. Further, I staunchly disagree with the idea that modifying environment variables is "bad practice". This is, quite literally, their intended purpose, and the reason why they're called "environment" variables is that they are inherited by subprocesses via `exec` syscalls. If they weren't meant to be modified, then the `setenv()` libc call wouldn't exist.

I would imagine `save()` gets removed entirely in v5. Don't quote me on that though. That would "fix" Webpack's incorrect usage of `process.env` for this package, but keep in mind that any other package that modifies environment variables is going to choke too. Please don't confuse webpack's behavior as "correct", because it's not. It's a hack.

**Comment by sapkra** [comment]
Thank your for your large response and all those information. I totally agree that webpack's behavior is a hack but you cannot just say that it is valid to change env vars on runtime, just because there is a function in libc for doing it.

This function does probably exist for some low level code or CLI tools, but maybe I'm wrong - I don't see any other reason why you should ever want to use something like this in a real application.

Anyway, we don't have to discuss about this topic for hours. Let's close it here. I'm looking forward to v5. :)

**Comment by sapkra** [comment]
I had another idea which might work for all of us. What about doing something like this:

```
process['env'].DEBUG = namespaces;
```

Then the DefinePlugin would not match the string `process.env` anymore. WDYT?

**Comment by Qix-** [comment]
There's nothing dynamic there, and that would violate our linter's rules. There's nothing stopping the bundler from constant folding that statement either.

This just isn't going to happen, sorry. Perhaps ask Webpack to allow you to disable their hacks?
